name: Deploy Medusa to CapRover

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bundle and Deploy
        run: |
          # 1. Kiểm tra xem chúng ta đang ở đâu (để debug nếu cần)
          ls -R
          
          # 2. Chui vào thư mục chứa code Medusa (Chỉ dùng 1 cấp thôi Zang nhé)
          cd my-medusa-store
          
          # 3. Đóng gói toàn bộ code bên trong thư mục này
          tar -cvf ../deploy.tar .
          
          # 4. Quay ra ngoài và đẩy file lên CapRover
          cd ..
          npx caprover deploy \
            --caproverUrl "${{ secrets.CAPROVER_SERVER_URL }}" \
            --appToken "${{ secrets.CAPROVER_APP_TOKEN }}" \
            --appName "zang-finance-app" \
            --tarFile "./deploy.tar"
