name: Deploy Medusa to CapRover

on:
  push:
    branches:
      - main  # Tự động deploy khi bạn push vào nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          # Địa chỉ Dashboard CapRover của bạn
          server: ${{ secrets.CAPROVER_SERVER_URL }}
          
          # Tên App chính xác trên CapRover
          app: 'zang-finance-app'
          
          # App Token lấy từ phần Deployment của App
          token: ${{ secrets.CAPROVER_APP_TOKEN }}
          path: ./my-medusa-store
